Add hacking section
nsxiv/nsxiv pull request #175
Opened 2021-11-23 23:36 UTC by XPhyro

This PR adds a hacking section in the readme and documents #76 and #146.

2021-11-24 03:16 UTC, N-R-K commented
I dont mind it, but I also feel like readme is getting a bit too crowded. Adding this to nsxiv-extra [CUSTOMIZATION](https://github.com/nsxiv/nsxiv-extra/blob/master/CUSTOMIZATION.md) and then linking it on the readme is also an option.

And now that I think about it, it seems like a better option since we already have some customization tips there. Adding it there would keep things unified.

2021-11-24 11:21 UTC, XPhyro commented
I'll open a PR in nsxiv-extra and convert this one to reference [CUSTOMIZATION](https://github.com/nsxiv/nsxiv-extra/blob/master/CUSTOMIZATION.md) in the readme.

2021-11-24 12:02 UTC, N-R-K commented
@XPhyro on nsxiv-extra, feel free to push directly. Also I would recommend using triple back-tick and then 'c' for codeblocks. It gives some nice syntax highlighting.
```c
int a = 5;
```

2021-11-24 12:12 UTC, XPhyro commented
In this repo we seem to be using the indent syntax, so I used the same syntax. I'll do so in the future.

Right now there isn't much that could benefit from syntax highlighting in the readme and the contents of this PR will be in nsxiv-extra; but for future-proofing, should we update the readme to use backticks (in a different PR)? Using two different syntaxes would make reading the source file weird.

2021-11-26 09:23 UTC, XPhyro commented
The nsxiv-extra commit is in: https://github.com/nsxiv/nsxiv-extra/commit/9aa41a44172ec4c995fd0e0cc7cead03c71620b3

Marking as ready for review.

2021-11-26 09:23 UTC, N-R-K requested changes

2021-11-26 09:23 UTC, N-R-K commented on README.md
> +nsxiv-extra's [README](https://github.com/nsxiv/nsxiv-extra/blob/master/README.md).
The repo already renders the README. Don't think we need to link to it specifically.
```suggestion
nsxiv-extra's [README](https://github.com/nsxiv/nsxiv-extra).
```

2021-11-26 09:23 UTC, N-R-K commented on README.md
> +pull request on this repository, then we *may* merge it to mainline.
Think this paragraph should be below the paragraph about limited scope.

2021-11-26 09:29 UTC, N-R-K approved these changes

2021-11-26 14:38 UTC, merged