Document development workflow
nsxiv/nsxiv pull request #202
Opened 2022-01-07 04:44 UTC by mamg22

Based on suggestions from https://github.com/nsxiv/nsxiv/discussions/119#discussioncomment-1882806

2022-01-07 08:02 UTC, N-R-K requested changes

2022-01-07 08:02 UTC, N-R-K commented on CONTRIBUTING.md
> +Our workflow regarding pull requests (PR) is:
This makes it sound like it's applicable to anyone sending a PR when reality it's only for maintainers.

2022-01-07 08:05 UTC, N-R-K commented
In the contributions guideline should add one more point:
* Avoid force pushes, especially for bigger patches. Only use them when there's merge conflicts.

2022-01-07 21:58 UTC, XPhyro requested changes

2022-01-07 21:58 UTC, XPhyro commented on CONTRIBUTING.md
> +    it reflects the intention of the PR.
```suggestion
    it reflects the current intention of the PR.
```

2022-01-07 22:00 UTC, XPhyro commented
We should also document the release process:
- The criteria of releasing a new version
- Tagging and release messages

2022-01-07 22:55 UTC, N-R-K commented
> * The criteria of releasing a new version
Don't think we have any. Obviously we don't want to tag a release if there's known major issue like compile failure with certain config, but that should be common sense and not really worth documenting.

2022-01-08 07:43 UTC, XPhyro approved these changes

2022-01-08 08:39 UTC, N-R-K requested changes

2022-01-08 08:39 UTC, N-R-K commented on CONTRIBUTING.md
> +    * Don't document internal, non user-visible changes.
```suggestion
    * Don't document changes which did not make it into a release.
```

2022-01-08 08:39 UTC, N-R-K commented on CONTRIBUTING.md
> +    * Separate each release with three dashes as separators, with a space
Don't think we need to be so verbose, three dash separator should be obvious.

2022-01-08 08:39 UTC, N-R-K commented on CONTRIBUTING.md
> +    * Include related pull request IDs after each item of the changelog, each
Same as above, I think these last 2 points should be obvious. We should only document non obvious things.

2022-01-08 15:07 UTC, XPhyro approved these changes

2022-01-08 15:08 UTC, N-R-K approved these changes

2022-01-08 15:09 UTC, merged